display_name: FlClash EX

packager: hoshiyomiX
packagerEmail: hoshiyomiX@users.noreply.github.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClash EX
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash EX

group: Applications/Internet

startup_notify: true
